database:
  postgres: "postgresql://postgres:mysecretpassword@localhost:5432/player"
  redis:
    address: "localhost:6379"
    password: ""
jwt_secret: "jMTpQCKTaXPwuJbxUMhuQhFQMwnWROzOakllnQhydMqgHXlcqnDxMazYObsv"